theme: jekyll-theme-minimal
title: Genespace
description: Open platform for bioinformatics

sass:
  style: compressed # possible values: nested expanded compact compressed

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
    - title: Блог
      url: /index.html
    - title: О проекте
      url: /project

social:
    github: genespace-ru
